### ISSUE TITLE
Use smarter position of the insertion

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-media-embed#12]
> The media widget is inserted always after the block in which you currently have the caret. The image insertion works a bit better and if you have the caret at the beginning of that block it gets inserter before it. This can be a followup, of course.

A follow-up of https://github.com/ckeditor/ckeditor5-media-embed/pull/2#issuecomment-414744266.

**Comment by pjasiun** [comment]
Similarly to my comments in the table feature (https://github.com/ckeditor/ckeditor5-table/issues/27#issuecomment-419917100 and https://github.com/ckeditor/ckeditor5-table/issues/27#issuecomment-419917623), it looks very inconsistent in Letters now.

Especially:
 - when the position is at the beginning of the block, it should be inserted before the block,
 - when the position is in the empty block it should be inserted instead of block.

This is now it looks like now:
![insert-before-after](https://user-images.githubusercontent.com/1166967/45301691-bcb74900-b511-11e8-9563-4eeeaabc30bc.gif)

![insert-empty](https://user-images.githubusercontent.com/1166967/45301698-c04ad000-b511-11e8-9a65-0066c84c27d6.gif)

**Comment by Reinmar** [comment]
Let's continue this discussion in https://github.com/ckeditor/ckeditor5/issues/1243.
