### ISSUE TITLE
Twitter's background makes focus outline nearly invisible

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-media-embed#22]
Is it selected or not?

![image](https://user-images.githubusercontent.com/156149/44649106-3ebc5380-a9e3-11e8-9661-993384bcd90a.png)

**Comment by dkonopka** [comment]
I would replace one color background to gradient (we are using gradient in instagram case):

![screen shot 2018-08-27 at 10 50 24](https://user-images.githubusercontent.com/10219857/44650474-0a4a9680-a9e7-11e8-81f4-c93a2a51fab7.png)


Changing lightness of "twitter color" isn't working well here IMHO:
### Darker bg ![screen shot 2018-08-27 at 10 30 19](https://user-images.githubusercontent.com/10219857/44649896-87750c00-a9e5-11e8-8d8b-38bbbc64c13a.png)

### Lighter bg (text to bg weak contrast)
![screen shot 2018-08-27 at 10 44 32](https://user-images.githubusercontent.com/10219857/44650271-6c56cc00-a9e6-11e8-82a6-615e06bc03ee.png)

**Comment by fredck** [comment]
Hard to have the inner box acquire a white/transparent background on selection/hover, right?

**Comment by Reinmar** [comment]
It should be possible with `box-shadow: inset`.

**Comment by dkonopka** [comment]
It's possible to add changed background or box-shadow on the selected box (see screencast).

The thing is it will be different behavior on selection than other media-embed elements (like yt, Instagram etc.). IMHO adding selection shadow for twitter means we should use for every `.ck-widget_selected` to be consistent (btw. it's not looks bad even inside images). 

That's why changing default Twitter background (to gradient) is the simplest idea. WDYT?

### Selected Twitter:
<img width="600" alt="screen shot 2018-08-27 at 11 43 31" src="https://user-images.githubusercontent.com/10219857/44653258-8694a800-a9ee-11e8-9938-e3c5ce291a76.png">

### Screencast:
![twitter-bg](https://user-images.githubusercontent.com/10219857/44653132-24d43e00-a9ee-11e8-9115-f396ae98194f.gif)


```css
figure.ck-widget_selected .ck-media__wrapper .ck.ck-media__placeholder {
    box-shadow: inset 0 0 10px hsla( 0, 0%, 0%, 0.35 );
}
```

**Comment by Reinmar** [comment]
I don't like that shadow. I was thinking more about something like:

![image](https://user-images.githubusercontent.com/156149/44654160-0de31b00-a9f1-11e8-9eaa-d5b26588d556.png)

But to add this I had to also add `padding: 1px` which isn't cool. In such case a gradient may be easier and safer.

**Comment by dkonopka** [comment]
☝️ I was trying with white (and smth darker) border inside too and it looks weird.
I'll prepare a PR with a gradient change then.
