### ISSUE TITLE
We need to make our mind about the initial configuration

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-media-embed#31]
Right now the feature is configured to support providers for which we have previews and some for which we don't.

Those for which we don't have previews are output as `<oembed>` and those for which we have as `<div sth>`. That meant to make the best use of two types of content providers.

However, the two main groups of this feature's adopters look like this:

* There's a group of developers who have no time, no possibility or simply a wish to use an oEmbed proxy (Iframely, Embedly, custom one). They need some quick solution. It can be limited, but that's ok.
* There's a group of developers who have time, resources, etc to use an oEmbed proxy. 

Currently, the feature needs to be configured by both groups. The first group needs to use `mediaEmbed.removeProviders` to limit the providers to previewable ones and the second group should use `mediaEmbed.semanticDataOutput` to keep the database clear.

We need to pick one of this groups and preconfigure the feature for it so at least some percentage of this feature's users don't have to change its configuration.

I'm for picking the latter group. Which means that `mediaEmbed.semanticDataOutput` will default to `true` which, in turn, means that it should be renamed to something like `mediaEmbed.outputPreviews` so it can default to `false`.

**Comment by Reinmar** [comment]
We should also re-read the docs because there's a great chance that they can be simplified. I think I would remove the entire part about replacing media with previews by iframely/embedly, which will make them simpler. But there's a chance we can remove even more text.

**Comment by pjasiun** [comment]
I agree with the post but I would make it work for the first group by default.

We are no able to make this plugin works out of the box for the second group and they will need to do additional work anyway, they will need to read docs and learn a little bit about the plugin.

However, for the first group, we can make this plugin working out of the box - you just enable it and get additional functionality (even if limited to only a few features). This way, some people, who do not want to learn details will get something.

Otherwise, if we will choose semantic output by default we require everyone to learn a little bit more to make this feature works, what is not what some people expect. And I can understand that some people, just want some cool stuff "for free", so not want to get into details (especially if the enable 20 features in one day and do not want to learn each of them separately).

**Comment by oleq** [comment]
In a F2F talk, it has been agreed that the semantic data output is the best because it allows us to demo the full potential of the feature (both previewable and preview–less media). If we went the opposite way, to use default config in our demos would mean a complete remval of non–previewable media providers from the configuration (Twitter, Instagra, Google Maps, etc.). 

Considering the limited set of default previewable media providers (there are just few), using the non–semantic data output would make the feature look poor and very limited to the visitors of our documentation, which is not true.
